name: Deploy Prodigy_Deployment Folder

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install rsync
      run: sudo apt-get install rsync

    - name: Deploy published files via rsync
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.LINUX_HOST }}
        username: ${{ secrets.LINUX_USER }}
        password: ${{ secrets.LINUX_PASSWORD }}
        script: |
          rsync -az --delete ./Prodigy_Deployment/ /home/nezuko/LeS/WebScrappers/LeS10072_LeS_Prodigy_Processor/
