name: Deploy to Linux via Password

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET App
      run: dotnet publish -c Release -o publish

    - name: Install rsync
      run: sudo apt-get install rsync

    - name: Deploy via rsync over SSH (with password)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.LINUX_HOST }}
        username: ${{ secrets.LINUX_USER }}
        password: ${{ secrets.LINUX_PASSWORD }}
        script: |
          rsync -az --delete ./publish/ /home/nezuko/LeS/WebScrappers/LeS10072_LeS_Prodigy_Processor/

    - name: Restart app (optional)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.LINUX_HOST }}
        username: ${{ secrets.LINUX_USER }}
        password: ${{ secrets.LINUX_PASSWORD }}
        script: |
          sudo systemctl restart myapp.service
